### ISSUE TITLE
About Training 

### ISSUE THREAD

**Issue by xianxuan-z** [HobbitLong/SupContrast#96]
I ran this code on my lab computer .
but got the error like following:
UserWarning: 
    There is an imbalance between your GPUs. You may want to exclude GPU 4 which
    has less than 75% of the memory or cores of GPU 0. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL Error 1: unhandled cuda error
I am very upset and confused.
Anyone can help me ?

**Comment by HobbitLong** [comment]
Hi, @xianxuan-z, I am not very sure. But it seems it complains that your GPU 4 might be a different model and has less memory, e.g., your GPU 0-2 could be Titan RTX, while your GPU 4 is 1080Ti.

My random guess is these two different GPU models might require different versions of NVIDIA driver or cuda version,  which leads to the error.

One way might be you run `CUDA_VISIBLE_DEVICES=0,1,2`.

As this is not relevant to the repo, I'll close it

**Comment by xianxuan-z** [comment]
Thank you so much! I have solved this problem.
1.torch version changed from 1.7.0 to 1.6.0
2. CUDA_VISIBLE_DEVICES="0,1,2,3" is set
The reason I changed the version was because I saw someone saying that when using a higher version of torch, the same problem as mine occurred.

在2021-12-13 02:39:35，Yonglong ***@***.***写道：

Hi, @xianxuan-z, I am not very sure. But it seems it complains that your GPU 4 might be a different model and has less memory, e.g., your GPU 0-2 could be Titan RTX, while your GPU 4 is 1080Ti.

My random guess is these two different GPU models might require different versions of NVIDIA driver or cuda version, which leads to the error.

One way might be you run CUDA_VISIBLE_DEVICES=0,1,2.

As this is not relevant to the repo, I'll close it

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
